### PR TITLE
Adding new feature: BlazeLayout.wrapRender

### PR DESCRIPTION
**Pull request by grsabreu**
It's really annoying to be calling over and over the same 
~~~js 
BlazeLayout.render("sameLayout", {top: 'header', main: 'clients'}); 
~~~

So this function wraps BlazeLayout.render and returns a function with a pre-defined layout.

~~~js
var dashboardRender = BlazeLayout.wrapRender('dashboardLayout');
// ... later, just call:

dashboardRender({content: 'clients'});
~~~

### CODE REVIEW

**Comment by grsabreu** [comment]
I did a mistype in the commit message, `Blaze` instead `BlazeLayout`
Sorry :p

**Comment by elidoran** [comment]
Why not use JavaScript's bind function to create the desired function?

```js
// this does the same thing...
var dashboardRender = BlazeLayout.render.bind(BlazeLayout, 'dashboardLayout');
// this function will use 'dashboardLayout' as its first argument.
dashboardRender({content: 'clients'});
```

**Comment by arunoda** [comment]
Hi,

This is a a great feature, but we want keep BlazeLayout simple as possible it could. So, I'll close this PR.
But there's a way to do this.

* Create a new package with this functionality
* Then send me a PR to the BlazeLayout README listing as additional packages.

**Comment by grsabreu** [comment]
Alright, men :D

**Comment by grsabreu** [comment]
Totally forgot `.bind` haha, @elidoran

**Pull request closed without merging**
